# Generated by Django 5.0.6 on 2024-05-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'edição',
                'verbose_name_plural': 'edições',
            },
        ),
    ]
