# Generated by Django 5.0.6 on 2024-05-28 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinas', '0001_initial'),
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('historia', models.TextField(blank=True, null=True, verbose_name='História')),
                ('apelido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apelido')),
                ('mote', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mote')),
                ('seita', models.TextField(blank=True, null=True, verbose_name='Seita')),
                ('aparencia', models.TextField(blank=True, null=True, verbose_name='Aparência')),
                ('refugio', models.TextField(blank=True, null=True, verbose_name='Refúgio')),
                ('cria_persona', models.TextField(blank=True, null=True, verbose_name='Criação de Personagens')),
                ('fraquezas', models.TextField(blank=True, null=True, verbose_name='Fraquezas')),
                ('organizacao', models.TextField(blank=True, null=True, verbose_name='Organização')),
                ('antecedentes', models.TextField(blank=True, null=True, verbose_name='Antecedentes')),
                ('estereotipos', models.TextField(blank=True, null=True, verbose_name='Estereótipos')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='Logo')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateField(auto_now=True, verbose_name='Atualizado em')),
                ('disciplinas', models.ManyToManyField(to='disciplinas.disciplina', verbose_name='Disciplinas')),
                ('livro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livros.livro', verbose_name='Livro')),
            ],
            options={
                'verbose_name': 'clã',
                'verbose_name_plural': 'clãs',
            },
        ),
    ]
