# Generated by Django 5.0.6 on 2024-05-23 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('nivel', models.SmallIntegerField(verbose_name='Nível')),
                ('disciplina', models.CharField(max_length=50, verbose_name='Disciplina')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('sistema', models.TextField(verbose_name='Sistema')),
                ('efeito', models.TextField(verbose_name='Efeito')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Cla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('historia', models.TextField(verbose_name='História')),
                ('mote', models.CharField(max_length=200, verbose_name='Mote')),
                ('aparencia', models.TextField(verbose_name='Aparência')),
                ('refugio', models.TextField(verbose_name='Refúgio')),
                ('criacao_personagens', models.TextField(verbose_name='Criação de Personagens')),
                ('organizacao', models.TextField(verbose_name='Organização')),
                ('estereotipos', models.TextField(verbose_name='Estereótipos')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.edicao', verbose_name='Edição')),
                ('disciplinas', models.ManyToManyField(to='clas.disciplina', verbose_name='Disciplinas')),
            ],
            options={
                'verbose_name': 'clã',
                'verbose_name_plural': 'clãs',
            },
        ),
    ]
