# Generated by Django 5.0.6 on 2024-05-23 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clas', '0002_alter_cla_aparencia_alter_cla_criacao_personagens_and_more'),
        ('users', '0002_alter_edicao_atualizado_em_alter_edicao_criado_em_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cla',
            old_name='criacao_personagens',
            new_name='cria_persona',
        ),
        migrations.RemoveField(
            model_name='cla',
            name='edicao',
        ),
        migrations.AddField(
            model_name='cla',
            name='livro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.livro', verbose_name='Livro'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='livro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.livro', verbose_name='Livro'),
        ),
        migrations.AlterField(
            model_name='cla',
            name='atualizado_em',
            field=models.DateField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='cla',
            name='criado_em',
            field=models.DateField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='atualizado_em',
            field=models.DateField(auto_now=True, verbose_name='Update'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='criado_em',
            field=models.DateField(auto_now_add=True, verbose_name='Criacao'),
        ),
    ]
