# Generated by Django 5.0.6 on 2024-05-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clas', '0004_cla_antecedentes_cla_apelido_cla_fraquezas_cla_seita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cla',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='Logo'),
        ),
    ]
