# Generated by Django 5.0.6 on 2024-05-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clas', '0005_cla_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cla',
            name='logo',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='logo', verbose_name='Logo', width_field=100),
        ),
    ]
