# Generated by Django 5.0.6 on 2024-05-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clas', '0006_alter_cla_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cla',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='Logo'),
        ),
    ]
