# Generated by Django 5.0.6 on 2024-05-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clas', '0007_alter_cla_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='atualizado_em',
            field=models.DateField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='criado_em',
            field=models.DateField(auto_now_add=True, verbose_name='Criado em'),
        ),
    ]
