# Generated by Django 5.0.6 on 2024-05-31 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('regiao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Região')),
                ('dimensao', models.CharField(blank=True, choices=[('1', 'Terreno'), ('2', 'Umbra rasa'), ('3', 'Umbra media'), ('4', 'Umbra profunda'), ('5', 'Sonhar proximo'), ('6', 'Sonha distante'), ('7', 'Sonhar profundo'), ('8', 'Teia digital')], max_length=3, null=True, verbose_name='Dimensão')),
                ('era', models.CharField(blank=True, max_length=100, null=True, verbose_name='Era')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('autualizado_em', models.DateField(auto_now=True, verbose_name='Atualizado em')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.livro', verbose_name='Livro')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locals',
            },
        ),
    ]
