# Generated by Django 5.0.6 on 2024-05-23 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clas', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('editora', models.CharField(max_length=100, verbose_name='Editora')),
                ('revisao', models.CharField(max_length=50, verbose_name='Revisão')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.edicao', verbose_name='Edição')),
            ],
            options={
                'verbose_name': 'livro',
                'verbose_name_plural': 'livros',
            },
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('alcunha', models.CharField(blank=True, max_length=100, verbose_name='Alcunha')),
                ('mote', models.TextField(blank=True, verbose_name='Mote')),
                ('ficha', models.URLField(verbose_name='Ficha')),
                ('nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('cla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clas.cla', verbose_name='Clã')),
                ('disciplinas', models.ManyToManyField(to='clas.disciplina', verbose_name='Disciplinas')),
            ],
        ),
    ]
