# Generated by Django 5.0.6 on 2024-05-29 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clas', '0001_initial'),
        ('disciplinas', '0001_initial'),
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('alcunha', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alcunha')),
                ('mote', models.TextField(blank=True, null=True, verbose_name='Mote')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Biografia')),
                ('ficha_url', models.URLField(blank=True, null=True, verbose_name='Ficha URL')),
                ('ficha_pdf', models.FileField(upload_to=None, verbose_name='Ficha PDF')),
                ('nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('abraco', models.DateField(blank=True, null=True, verbose_name='Abraço')),
                ('morte_final', models.DateField(blank=True, null=True, verbose_name='Morte Final')),
                ('geracao', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Geração')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateField(auto_now=True, verbose_name='Atualizado em')),
                ('cla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clas.cla', verbose_name='Clã')),
                ('disciplinas', models.ManyToManyField(to='disciplinas.disciplina', verbose_name='Disciplinas')),
                ('livro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livros.livro', verbose_name='Edição')),
                ('senhor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personagens.personagem', verbose_name='Senhor')),
            ],
            options={
                'verbose_name': 'Personagem',
                'verbose_name_plural': 'Personagens',
            },
        ),
    ]
