# Generated by Django 5.0.6 on 2024-05-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='revisao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Revisão'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='alcunha',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alcunha'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='ficha',
            field=models.URLField(blank=True, null=True, verbose_name='Ficha'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='mote',
            field=models.TextField(blank=True, null=True, verbose_name='Mote'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
