# Generated by Django 5.0.6 on 2024-05-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='ficha_pdf',
            field=models.FileField(blank=True, null=True, upload_to=None, verbose_name='Ficha PDF'),
        ),
    ]
