# Generated by Django 5.0.6 on 2024-05-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0002_alter_personagem_ficha_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='ficha_pdf',
            field=models.FileField(blank=True, null=True, upload_to='fichas/', verbose_name='Ficha PDF'),
        ),
    ]
