# Generated by Django 5.0.6 on 2024-05-23 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clas', '0004_cla_antecedentes_cla_apelido_cla_fraquezas_cla_seita_and_more'),
        ('personagens', '0004_alter_personagem_alcunha'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='abraco',
            field=models.DateField(blank=True, null=True, verbose_name='Abraço'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='biografia',
            field=models.TextField(blank=True, null=True, verbose_name='Biografia'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='geracao',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Geração'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='senhor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personagens.personagem', verbose_name='Senhor'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='alcunha',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alcunha'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='atualizado_em',
            field=models.DateField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='cla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clas.cla', verbose_name='Clã'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='criado_em',
            field=models.DateField(auto_now_add=True, verbose_name='Criado en'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='mote',
            field=models.TextField(blank=True, null=True, verbose_name='Mote'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
