# Generated by Django 5.0.6 on 2024-05-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0005_personagem_abraco_personagem_biografia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='morte_final',
            field=models.DateField(blank=True, null=True, verbose_name='Morte final'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado en'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='ficha',
            field=models.URLField(blank=True, null=True, verbose_name='Ficha'),
        ),
    ]
