# Generated by Django 5.0.6 on 2024-05-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0006_personagem_morte_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='morte_final',
            field=models.DateField(blank=True, null=True, verbose_name='Morte Final'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
