# Generated by Django 5.0.6 on 2024-05-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0007_alter_personagem_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='atualizado_em',
            field=models.DateField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='criado_em',
            field=models.DateField(auto_now_add=True, verbose_name='Criado em'),
        ),
    ]
